# Generated by Django 4.2.3 on 2023-07-14 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomSite',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('device_photo', models.ImageField(upload_to='device_photos')),
                ('currency', models.CharField(max_length=20)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('referral_code', models.CharField(max_length=10)),
                ('lead_status', models.CharField(choices=[('Pending', 'Pending'), ('In-progress', 'In-progress'), ('Converted', 'Converted'), ('Rejected', 'Rejected')], max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webPageApp.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webPageApp.country')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webPageApp.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webPageApp.country')),
                ('managed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalkIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=20)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('walkin_datetime', models.DateTimeField()),
                ('token_number', models.IntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webPageApp.device')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webPageApp.lead')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webPageApp.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='sourced',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='webPageApp.vendor'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webPageApp.country'),
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webPageApp.customsite')),
                ('title', models.CharField(max_length=255)),
                ('allowed_devices', models.ManyToManyField(to='webPageApp.device')),
            ],
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='section_images')),
                ('html_content', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webPageApp.webpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
