# Generated by Django 4.2.3 on 2023-07-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPageApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_photo',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
