# Generated by Django 4.2.3 on 2023-07-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPageApp', '0002_alter_device_device_photo_alter_pagesection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
