# Generated by Django 4.2.3 on 2023-07-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPageApp', '0003_alter_pagesection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_photo',
            field=models.ImageField(upload_to='device'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='image',
            field=models.ImageField(upload_to='section'),
        ),
    ]
