# Generated by Django 4.2.3 on 2023-07-19 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('webPageApp', '0004_alter_device_device_photo_alter_pagesection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sites.site'),
        ),
        migrations.DeleteModel(
            name='CustomSite',
        ),
    ]
