# Generated by Django 4.2.3 on 2023-07-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPageApp', '0005_alter_webpage_site_delete_customsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='image',
            field=models.ImageField(blank=True, upload_to='section'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Enter the order of the section (lower value appears first).'),
        ),
    ]
